### ISSUE TITLE
Bug in UnescapeJSONStringToken

### ISSUE THREAD

**Issue by DutchFox2** [DagAgren/SmallJSONParser#1]
Hi!
First of all, thanks for this nice little library!
I encountered a problem in UnescapeJSONStringToken(): it turned out that the 0-terminator was placed in the first position of the dest string (making all results zero-length strings).
I think this:

```
        else
        {
            *dest=c;
        }
```

should be changed into:

```
        else
        {
            *dest++=c;
        }
```

**Comment by DagAgren** [comment]
Oh, this is because I have not been able to properly update this mirror repo from the original one at Bitbucket. You should probably use that one for the moment.

**Comment by DagAgren** [comment]
Finally got the hg-git push to work. This isn't the most reliable technology I've ever used... Either way, should be up to date now.
